# Generated by Django 6.0.1 on 2026-04-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_icon_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_question',
            field=models.BooleanField(default=False, verbose_name='Это вопрос'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'На рассмотрении'), ('in_progress', 'В работе'), ('accepted', 'Принят в работу'), ('completed', 'Завершён')], default='pending', max_length=20, verbose_name='Статус вопроса'),
        ),
    ]
