# Generated by Django 6.0.1 on 2026-04-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_requestuser_request_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestuser',
            options={'verbose_name': 'Заявка пользователя', 'verbose_name_plural': 'Заявки пользователей'},
        ),
    ]
