# Generated by Django 6.0.1 on 2026-04-20 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_requestuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('water', 'Холодное водоснабжение'), ('sewerage', 'Водоотведение'), ('hot_water', 'Горячее водоснабжение')], max_length=20, unique=True, verbose_name='Тип услуги')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу (руб/м³)')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['service_type', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='LkMeterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_number', models.CharField(max_length=50, verbose_name='Номер прибора')),
                ('service_type', models.CharField(choices=[('water', 'Холодное водоснабжение'), ('sewerage', 'Водоотведение'), ('hot_water', 'Горячее водоснабжение')], max_length=20, verbose_name='Тип услуги')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('initial_reading', models.IntegerField(default=0, verbose_name='Начальные показания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прибор учёта',
                'verbose_name_plural': 'Приборы учёта',
                'ordering': ['user', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='LkMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('current_reading', models.IntegerField(verbose_name='Текущие показания')),
                ('previous_reading', models.IntegerField(editable=False, verbose_name='Предыдущие показания')),
                ('consumption', models.IntegerField(editable=False, verbose_name='Расход (м³)')),
                ('amount_due', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма к оплате (руб)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='home.lkmeterdevice')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.settingstariff')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
