# Generated by Django 6.0.1 on 2026-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_settingstariff_lkmeterdevice_lkmeterreading'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lkmeterdevice',
            table='lk_meter_device',
        ),
        migrations.AlterModelTable(
            name='lkmeterreading',
            table='lk_meter_reading',
        ),
        migrations.AlterModelTable(
            name='settingstariff',
            table='settings_tariff',
        ),
    ]
