# Generated by Django 6.0.1 on 2026-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_lkmeterdevice_table_alter_lkmeterreading_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settingstariff',
            table='lk_settings_tariff',
        ),
    ]
