# Generated by Django 6.0.1 on 2026-04-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_settingstariff_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkmeterdevice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='home.client'),
        ),
    ]
