# Generated by Django 6.0.1 on 2026-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_lkmeterdevice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkmeterdevice',
            name='installation_date',
        ),
        migrations.AddField(
            model_name='lkmeterdevice',
            name='verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterModelTable(
            name='settingstariff',
            table='settings_tariff',
        ),
    ]
