# Generated by Django 6.0.1 on 2026-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_lkmeterdevice_installation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_start_day', models.PositiveSmallIntegerField(default=20, help_text='Число месяца, с которого разрешена подача показаний', verbose_name='День начала приёма показаний')),
                ('reading_end_day', models.PositiveSmallIntegerField(default=25, help_text='Число месяца, до которого разрешена подача (включительно)', verbose_name='День окончания приёма показаний')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
