# Generated by Django 6.0.1 on 2026-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_multiple_readings',
            field=models.BooleanField(default=False, help_text='Если отключено, пользователь может подать показания только 1 раз за период', verbose_name='Разрешить несколько подач в периоде'),
        ),
    ]
