# Generated by Django 6.0.1 on 2026-04-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sitesettings_allow_multiple_readings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Текущий баланс (задолженность)')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to='home.client')),
            ],
            options={
                'verbose_name': 'Лицевой счёт',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
    ]
