# Generated by Django 6.0.1 on 2026-04-27 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_personalaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='account_number',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='Номер лицевого счёта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес помещения'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата открытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО абонента'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО заявителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес помещения')),
                ('ownership_document', models.FileField(upload_to='account_requests/%Y/%m/', verbose_name='Правоустанавливающий документ (ЕГРН/договор)')),
                ('passport_copy', models.FileField(upload_to='account_requests/%Y/%m/', verbose_name='Копия паспорта')),
                ('snils_copy', models.FileField(blank=True, null=True, upload_to='account_requests/%Y/%m/', verbose_name='Копия СНИЛС')),
                ('meter_documents', models.FileField(blank=True, null=True, upload_to='account_requests/%Y/%m/', verbose_name='Документы на приборы учёта')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на открытие счета',
                'verbose_name_plural': 'Заявки на открытие счета',
            },
        ),
    ]
