# Generated by Django 6.0.1 on 2026-04-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_personalaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_accounts', to='home.client'),
        ),
    ]
