# Generated by Django 6.0.1 on 2026-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_personalaccount_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='applicant_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо / ИП')], default='individual', max_length=20, verbose_name='Тип заявителя'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='manager_position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность руководителя'),
        ),
    ]
