# Generated by Django 6.0.1 on 2026-05-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_accountrequest_applicant_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkmeterdevice',
            name='client',
        ),
        migrations.AddField(
            model_name='lkmeterdevice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='home.personalaccount'),
        ),
    ]
